
server:
  port: 8080
  error:
    include-stacktrace: never


  # application:
  #   name: cadastrocia
    
spring:
 data:
   mongodb:
     host: "roundhouse.proxy.rlwy.net"
     port: "17036"
     database: "cadastrocia"
     username: "mongo"
     password: "HcffdHGe65-d-E23efEE415562egg4bG"




# Configurações de segurança (opcional)
# security:
#   user:
#     name: seu-usuario
#     password: sua-senha
#     roles: USER

# Configurações do Thymeleaf (opcional)
# thymeleaf:
#   prefix: classpath:/templates/
#   suffix: .html
#   cache: false

# Configurações de internacionalização (opcional)
# spring:
#   messages:
#     basename: messages
#     encoding: UTF-8
#     cache-seconds: 3600

# Configurações do Swagger (opcional)
# springfox:
#   documentation:
#     enabled: true

# Configurações do Lombok (opcional)
# lombok:
#   config:
#     debug: true

# Outras configurações específicas do seu projeto
# advocacia:
#   propriedade: valor
